In [1]:
import numpy as np
import pandas as pd

In [2]:
gulf = pd.read_pickle('gulf')
taxi = pd.read_pickle('taxi')

In [23]:
gulf.head()

city  start_long  start_lat   end_long   end_lat           start_time  \
0  北京市   116.32343   39.89747  116.30094  39.88813  2016-12-22 08:17:45   
1  北京市   116.29758   39.92169  116.20081  39.93249  2016-12-22 00:11:44   
2  北京市   116.34038   40.04395  116.39757  39.90693  2016-12-24 06:50:03   
3  北京市   116.47050   39.90030  116.47661  39.86796  2016-12-22 00:09:22   
4  北京市   116.49607   39.92822  116.46900  39.95150  2016-12-22 00:07:36   

              end_time  type  label  
0  2016-12-22 08:27:06  gulf      0  
1  2016-12-22 00:24:21  gulf      0  
2  2016-12-24 07:20:35  gulf      0  
3  2016-12-22 00:23:39  gulf      0  
4  2016-12-22 00:20:11  gulf      0

In [36]:
label

NameError: name 'label' is not defined

In [12]:
unique, counts = np.unique(gulf.label, return_counts=True)


In [22]:
unique

array([                  0,      97148620203148,      97159731897388, ...,
       9222061816955460216, 9222061817466862878, 9222061822214211013])

In [13]:
counts[::-1].sort()

In [35]:
counts[:-100]

array([458213,      3,      3, ...,      1,      1,      1])

In [7]:
gulf.shape

(545714, 9)

In [18]:
(545714 - 458213) / ( 160357 + 545714)

0.12392663060797002

array([                  0,      97148620203148,      97159731897388, ...,
       9222061816955460216, 9222061817466862878, 9222061822214211013])